name: Deploy Next.js application

on:
  push:
  branches:
    - main

job:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4
      - name: Create .env file
        run: echo "MONGO_PASSWORD=${{ secrets.MONGO_PASSWORD }}" >> .env && echo "SITE_URL=${{ secrets.SITE_URL }}" >> .env 
      - name: Build Docker image
        run: docker build -t baksish247/hungrymonk .
      - name: Login to DockerHub
        run: docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_PASSWORD}}
      - name: Push Docker image to Docker Hub
        run: docker push baksish247/hungrymonk:latest
  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Pull Docker image from Docker Hub
        run: docker pull baksish247/hungrymonk:latest
      - name: Delete Old Docker Image
        run: docker rm -f baksish_hmonk_ec2
      - name: Run Docker Container
        run: docker run -d -p 3000:3000 --name baksish_hmonk_ec2 baksish247/hungrymonk